# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50d6337c83b9a98ebee2565fc5b6a907e96c39b2776660d172d97749c988908489bb98191c49ec79fc9f65eb8c5759111b60bbd10460fdf48be0dc8c018e0c09

test:
  secret_key_base: 61084590a1c32e9621faec5a5333a721c02d2455a21ca75452ab0219850b8729780b856d96ee2b327f4c0396aed17a396f2b91ca305c944cd8eba9a6b997288a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
